require('core/events')
require('core/debug_manager')
require('core/game_manager')
require('core/game_clock')
require('core/score_manager')
require('core/passive_gold')
require('core/global_messages')
require('core/speed_boosts')
require('core/rune_spawner')
require('core/patrol_golems')

require("core/filters/init")