require('core/events')
require('core/game_manager')
require('core/game_clock')
require('core/score_manager')
require('core/gold_rewards')
require('core/global_messages')
require('core/powerups')
require('core/boss_manager')
require('core/debug_commands')

require('core/nexus')
require('core/lane_creeps')

require("core/filters/init")
require("core/rts/init")