-- require('core/speed_boosts')
-- require('core/patrol_golems')
-- require('core/shrines')
-- require('core/objectives')
-- require('core/tower')
-- require('core/portals')
-- require('core/push_cart')
-- require('core/ball_abilities')
-- require('core/wall')

require('core/events')
require('core/debug_manager')
require('core/game_manager')
require('core/game_clock')
require('core/score_manager')
require('core/gold_rewards')
require('core/global_messages')
require('core/runes')
require('core/lane_creep')
require('core/neutral_camps')
require('core/nexus')
require('core/firelands')
require('core/archer_coins')
require('core/buildables')

require("core/filters/init")
require("core/ctf/init")